name: Setup D&D Brewery Project

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/setup.yml'

jobs:
  setup:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Create project structure
      run: |
        mkdir -p src/{components,screens,styles,utils,types,navigation}

    - name: Create package.json
      run: |
        cat > package.json << 'EOF'
        {
          "name": "dnd-brewery-mobile",
          "version": "0.0.1",
          "private": true,
          "scripts": {
            "android": "react-native run-android",
            "ios": "react-native run-ios", 
            "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
            "start": "react-native start",
            "test": "jest",
            "type-check": "tsc --noEmit"
          },
          "dependencies": {
            "react": "18.2.0",
            "react-native": "0.72.6",
            "react-native-markdown-display": "^7.0.2",
            "react-native-vector-icons": "^10.0.3",
            "@react-native-async-storage/async-storage": "^1.19.3",
            "react-native-paper": "^5.10.6",
            "react-native-safe-area-context": "^4.7.4",
            "react-native-screens": "^3.25.0",
            "@react-navigation/native": "^6.1.9",
            "@react-navigation/stack": "^6.3.20",
            "react-native-gesture-handler": "^2.13.4"
          },
          "devDependencies": {
            "@babel/core": "^7.20.0",
            "@babel/preset-env": "^7.20.0",
            "@babel/runtime": "^7.20.0",
            "@react-native/eslint-config": "^0.72.2",
            "@react-native/metro-config": "^0.72.11",
            "@tsconfig/react-native": "^3.0.0",
            "@types/react": "^18.0.24",
            "@types/react-test-renderer": "^18.0.0",
            "babel-jest": "^29.2.1",
            "eslint": "^8.19.0",
            "jest": "^29.2.1",
            "metro-react-native-babel-preset": "0.76.8",
            "prettier": "^2.4.1",
            "react-test-renderer": "18.2.0",
            "typescript": "4.8.4"
          },
          "jest": {
            "preset": "react-native"
          }
        }
        EOF

    - name: Create types file
      run: |
        cat > src/types/index.ts << 'EOF'
        export interface Document {
          id: string;
          title: string;
          content: string;
          createdAt: Date;
          updatedAt: Date;
        }

        export interface StatBlock {
          name: string;
          type: string;
          ac: number;
          hp: string;
          speed: string;
          abilities: {
            str: number;
            dex: number;
            con: number;
            int: number;
            wis: number;
            cha: number;
          };
          savingThrows?: string;
          skills?: string;
          damageResistances?: string;
          senses?: string;
          languages?: string;
          challenge?: string;
        }

        export interface BrewerySettings {
          theme: 'light' | 'dark';
          fontSize: number;
          previewMode: 'split' | 'preview' | 'editor';
          autoSave: boolean;
        }
        EOF

    - name: Create colors file
      run: |
        cat > src/styles/colors.ts << 'EOF'
        export const colors = {
          parchment: '#F4F1E8',
          inkBlack: '#2C1810',
          burgundy: '#8B0000',
          gold: '#D4AF37',
          forestGreen: '#228B22',
          primary: '#8B0000',
          secondary: '#D4AF37',
          background: '#F4F1E8',
          surface: '#FFFFFF',
          text: '#2C1810',
          textSecondary: '#5D4E37',
          border: '#D2B48C',
          success: '#4CAF50',
          warning: '#FF9800',
          error: '#F44336',
          info: '#2196F3',
          editorBackground: '#FAFAFA',
          editorText: '#333333',
          lineNumbers: '#999999',
          selection: '#B3D4FC',
        };
        EOF

    - name: Create config files
      run: |
        cat > tsconfig.json << 'EOF'
        {
          "extends": "@tsconfig/react-native/tsconfig.json"
        }
        EOF

        cat > metro.config.js << 'EOF'
        const {getDefaultConfig, mergeConfig} = require('@react-native/metro-config');
        const defaultConfig = getDefaultConfig(__dirname);
        const config = {};
        module.exports = mergeConfig(defaultConfig, config);
        EOF

        cat > babel.config.js << 'EOF'
        module.exports = {
          presets: ['module:metro-react-native-babel-preset'],
        };
        EOF

    - name: Install dependencies
      run: npm install

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Automated setup: Initialize D&D Brewery React Native project" || exit 0
        git push